#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
x=1
while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    elif [ $x -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((x++))
done
